// import { Inter } from 'next/font/google'
// import './globals.css'
import { Container } from 'react-bootstrap';
import styled, { createGlobalStyle } from 'styled-components';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const GlobalStyle = createGlobalStyle`
  body {
    background-color: #e9ecef;
  }
`;

const StyledContainer = styled(Container)`
  margin-top: 20px;
`;

export default function RootLayout({ children }) {
  return (
    <>
      <GlobalStyle />
      <StyledContainer>{children}</StyledContainer>
    </>
  );
}


